[package]
name = "desk"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
cash = { path = "../cash" }
oracle = { path = "../oracle" }
equity = { path = "../equity" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
cash = { path = "../cash" }
oracle = { path = "../oracle" }
equity = { path = "../equity" }
